#!/bin/bash
#script post reinstall mac for jamf

#Function choose name
namechoose () {
    echo "Entrer le nom de la machine :";
    read nom;
}

#Function do action
runactions () {
    sudo scutil --set HostName $nom;
    sudo scutil --set LocalHostName $nom;
    sudo scutil --set ComputerName $nom;
    echo Rename Successful
    echo Renew profiles ...
    sudo profiles renew -type enrollment;
    echo Checkling Jamf policy ...
    sudo jamf policy;
}

while true; do

namechoose;

read -p "Computer name is $nom right ? (yes/no)" yn

case $yn in 
    yes ) runactions;
        break;;
    no  ) echo relunch;;
esac

done 



 


